### ISSUE TITLE
post_install: dump the parsed configuration to conf/<timestamp>-rose-suite.conf

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-rose#10]
https://cylc.github.io/cylc-admin/proposal-rose-suite-run.html#log-file-changes

**Comment by wxtim** [comment]
### To-do list:
- [ ] Create `INSTALL_DIR/conf/<datestamp>-rose-suite.conf` and copy final output of `cylc-rose`'s `rose-suite.conf` to it.
- [ ] Create a directory `INSTALL_DIR/install` - Inside this create:
- [ ] install/<timestamp>-install.log (replaces rose-suite-run.log) - file with the logs for the plugin?
- [ ] install/<timestamp>-reload.log (currently appended to rose-suite-run.log) - not yet sure. Will we do this by detection of earlier files or by passing info from Cylc CLI?
- [ ] install/<timestamp>-vc.log (replaces rose-conf/*.version)

**Comment by oliver-sanders** [comment]
> Create INSTALL_DIR/conf/<datestamp>-rose-suite.conf

`INSTALL_DIR/log/conf/`

(the idea is that `log/suiterc` will be renamed `log/conf`, however, that will require a separate PR in cylc-flow later)

**Comment by oliver-sanders** [comment]
```bash
cylc-run/
  flow-name/
    run-name/
      flow.cylc
      rose-suite.conf
      log/
        conf/
          # used to be suiterc, currently flow-config
          <timestamp>-<run|restart>.cylc  # <run|restart> will soon just be play
          <timestamp>-rose-suite.conf
        install/
          # new dir for saving `cylc install` log output
          <timestamp>-install.log  # for installation and reinstallation log
          <timestamp>-vc  # for installation version control log
```

The `install/-reload.log` log is a typo, have opened a cylc-admin PR to fix. Suggest that subsequent re-installations should just use the name `install`.

**The only bit of this that applies to cylc-rose is the conf/<timestamp>-rose-suite.conf**

The rest we can do in `cylc-flow`.
